run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: litmuschaos-mcp-server
  
  golint:
    min-confidence: 0.8
  
  govet:
    check-shadowing: true
    enable-all: true
  
  misspell:
    locale: US
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  
  disable:
    - interfacer
    - maligned
    - scopelint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    - linters:
        - lll
      source: "^//go:generate "
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false